version: '2.2'

services:
  showcase:
    restart: always
    container_name: beatitud_showcase
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
    - 4000:4000
    volumes:
    - .:/srv/jekyll